### ISSUE TITLE
Mapa mental 1 "B" Kevin Osorio Aparicio

### ISSUE THREAD

**Issue by KevinOsorio23143** [SistemasTecTlaxiaco/actividad-1-mapa-mental-KevinOsorio23143#1]
[Mapa mental.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-KevinOsorio23143/files/9466530/Mapa.mental.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica, has obtenido un 16.8% del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
